let keys = {}

keys.privateKey = `MIGpAgEAAiBl08DJewavOj3Dc5SFcdVzRUQrrYHnAuJxmyWrfAQspwIDAQABAiBL
YyJwCG1CfdQMSB3FTinAYrLzESTZoQtAeJNQ1vsdAQIRAMEs+3LdvZ1hTyDkqbDL
IJcCEQCG8XcI60UY04/HmpFgysZxAhA8vacm/CBGHzXhUuUkiQprAhAyVuGQ8jNU
j5eTXpXdBcgBAhEAkyAvghYXi6oGMOUbNz9bXQ==`
keys.publicKey = `MDswDQYJKoZIhvcNAQEBBQADKgAwJwIgZdPAyXsGrzo9w3OUhXHVc0VEK62B5wLi
cZslq3wELKcCAwEAAQ==`

module.exports = keys;